{% set name = "happly" %}
{% set version = "0.0.0.2020.8.22" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/nmwsharp/happly/archive/8a606309daaa680eee495c8279feb0b704148f4a.zip
  sha256: 1187131adbfd087b01e57863678e3fb91304d8ed8ad25f56ac8329ea8b31cca9

build:
  noarch: generic
  number: 0

test:
  commands:
    - test -f ${PREFIX}/include/happly.h  # [unix]
    - if not exist %PREFIX%\\Library\\include\\happly.h exit 1  # [win]

about:
  home: https://github.com/nmwsharp/happly
  summary: A header-only C++ reader/writer for the PLY file format. Parse .ply happily!
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - ytausch
